"use client";
import { useEffect, useMemo, useState } from "react";
import { Download } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { LoadingBlock } from "@/components/ui/loading";
import { apiFetch } from "@/lib/client-api";
import { useLookups } from "@/lib/use-lookups";
import { formatMoney, formatPercent } from "@/lib/money";
import { MONTHS_PT, currentCompetence, formatDate } from "@/lib/date";

export default function ConferencePage(){
 const lookups=useLookups();const[year,setYear]=useState(currentCompetence().slice(0,4));const[project,setProject]=useState("all");const[rows,setRows]=useState<any[]>([]);const[allocations,setAllocations]=useState<any[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{setLoading(true);Promise.all([apiFetch<any[]>("/api/crud/transactions?limit=2000"),apiFetch<any[]>("/api/crud/allocations?limit=4000")]).then(([t,a])=>{setRows(t.filter(x=>!x.archived));setAllocations(a)}).finally(()=>setLoading(false));},[]);
 const projectMap=useMemo(()=>new Map(lookups.projects.map(p=>[p.id,p.name])),[lookups.projects]),catMap=useMemo(()=>new Map(lookups.categories.map(c=>[c.id,c.name])),[lookups.categories]);
 const yearRows=rows.filter(r=>r.competence_month?.startsWith(year));
 const visible=yearRows.filter(r=>project==="all"?true:project==="holding"?!r.project_id:r.project_id===project);
 const monthSummaries=Array.from({length:12},(_,idx)=>{const month=`${year}-${String(idx+1).padStart(2,"0")}`;const base=yearRows.filter(r=>r.competence_month?.startsWith(month));let relevant=base;if(project!=="all")relevant=project==="holding"?base.filter(r=>!r.project_id):base.filter(r=>r.project_id===project);let gross=0,fees=0,costs=0;for(const r of relevant){if(r.transaction_type==="revenue"&&r.status==="received"){gross+=Number(r.gross_amount_cents);fees+=Number(r.fee_amount_cents)}else if(r.transaction_type==="cost"&&r.status==="paid"){if(project!=="all"&&project!=="holding"&&r.cost_scope!=="direct")continue;costs+=Number(r.gross_amount_cents)+Number(r.fee_amount_cents)}}if(project!=="all"&&project!=="holding"){const sharedInMonth=base.filter(r=>r.transaction_type==="cost"&&r.cost_scope==="shared"&&r.status==="paid");const sharedIds=new Set(sharedInMonth.map(r=>r.id));costs+=allocations.filter(a=>a.project_id===project&&sharedIds.has(a.transaction_id)).reduce((s,a)=>s+Number(a.allocated_amount_cents),0)}const net=gross-fees,profit=net-costs;return{month:MONTHS_PT[idx],gross,fees,net,costs,profit,margin:gross?profit/gross*100:null}});
 const totals=monthSummaries.reduce((a,m)=>({gross:a.gross+m.gross,fees:a.fees+m.fees,net:a.net+m.net,costs:a.costs+m.costs,profit:a.profit+m.profit}),{gross:0,fees:0,net:0,costs:0,profit:0});
 return <><PageHeader title="Conferência" description="Visão deliberadamente próxima da planilha para conferir o sistema durante a transição." actions={<a className="button button-secondary" href={`/api/export/finance?format=xlsx&year=${year}${project==="holding"?"&holding=1":project!=="all"?`&project_id=${project}`:""}`}><Download size={15}/> Exportar XLSX</a>}/><div className="filter-bar"><div className="field"><label>Ano</label><input className="input" type="number" value={year} onChange={e=>setYear(e.target.value)}/></div><div className="field"><label>Projeto</label><select className="select" value={project} onChange={e=>setProject(e.target.value)}><option value="all">Consolidado</option><option value="holding">Prodexy / Holding</option>{lookups.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></div>
 {project!=="all"&&project!=="holding"&&<div className="note" style={{marginBottom:14}}>Na visão de projeto, o resumo mensal inclui custos compartilhados rateados. A tabela detalhada mostra os lançamentos financeiros originais; rateios não são duplicados como novas transações.</div>}
 {loading?<LoadingBlock lines={8}/>:<><section className="panel table-wrap"><table><thead><tr><th>Data</th><th>Mês</th><th>Tipo</th><th>Categoria</th><th>Descrição</th><th className="numeric">Qtd.</th><th className="numeric">Valor unitário</th><th className="numeric">Valor bruto</th><th className="numeric">Taxa</th><th className="numeric">Valor líquido</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{formatDate(r.transaction_date)}</td><td>{r.competence_month?.slice(0,7)}</td><td><Badge tone={r.transaction_type==="revenue"?"positive":"negative"}>{r.transaction_type==="revenue"?"Receita":"Custo"}</Badge></td><td>{catMap.get(r.category_id)||"—"}</td><td><strong>{r.description}</strong>{project==="all"&&<div className="muted">{r.project_id?projectMap.get(r.project_id):"Prodexy / Holding"}</div>}</td><td className="numeric">{Number(r.quantity)}</td><td className="numeric">{formatMoney(r.unit_amount_cents)}</td><td className="numeric">{formatMoney(r.gross_amount_cents)}</td><td className="numeric">{formatMoney(r.fee_amount_cents)}</td><td className={`numeric ${r.net_amount_cents<0?"negative":""}`}>{formatMoney(r.net_amount_cents)}</td></tr>)}</tbody></table></section>
 <div className="section-title"><h2>Resumo mensal</h2><p>Janeiro a dezembro + total anual</p></div><section className="panel table-wrap"><table><thead><tr><th>Mês</th><th className="numeric">Receita bruta</th><th className="numeric">Taxas</th><th className="numeric">Receita líquida</th><th className="numeric">Custos</th><th className="numeric">Lucro</th><th className="numeric">Margem</th></tr></thead><tbody>{monthSummaries.map(m=><tr key={m.month}><td>{m.month}</td><td className="numeric">{formatMoney(m.gross)}</td><td className="numeric">{formatMoney(m.fees)}</td><td className="numeric">{formatMoney(m.net)}</td><td className="numeric">{formatMoney(m.costs)}</td><td className={`numeric ${m.profit<0?"negative":""}`}>{formatMoney(m.profit)}</td><td className="numeric">{m.margin==null?"—":formatPercent(m.margin)}</td></tr>)}<tr><td><strong>Total anual</strong></td><td className="numeric"><strong>{formatMoney(totals.gross)}</strong></td><td className="numeric"><strong>{formatMoney(totals.fees)}</strong></td><td className="numeric"><strong>{formatMoney(totals.net)}</strong></td><td className="numeric"><strong>{formatMoney(totals.costs)}</strong></td><td className={`numeric ${totals.profit<0?"negative":""}`}><strong>{formatMoney(totals.profit)}</strong></td><td className="numeric">{totals.gross?formatPercent(totals.profit/totals.gross*100):"—"}</td></tr></tbody></table></section></>}</>;
}
