"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, Plus, Split, Trash2 } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { EmptyState } from "@/components/ui/empty-state";
import { LoadingBlock } from "@/components/ui/loading";
import { apiFetch, crudDelete, crudUpdate } from "@/lib/client-api";
import { useLookups } from "@/lib/use-lookups";
import { formatMoney, moneyToCents } from "@/lib/money";
import { currentCompetence, formatDate, todayInSaoPaulo } from "@/lib/date";

export default function SharedCostsPage(){
  const lookups=useLookups(); const [transactions,setTransactions]=useState<any[]>([]); const [allocations,setAllocations]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [open,setOpen]=useState(false); const [error,setError]=useState("");
  const [date,setDate]=useState(todayInSaoPaulo()); const [month,setMonth]=useState(currentCompetence().slice(0,7)); const [description,setDescription]=useState(""); const [categoryId,setCategoryId]=useState(""); const [provider,setProvider]=useState(""); const [value,setValue]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [method,setMethod]=useState<"equal"|"manual">("equal"); const [manual,setManual]=useState<Record<string,string>>({}); const [saving,setSaving]=useState(false);
  const load=async()=>{setLoading(true);try{const [t,a]=await Promise.all([apiFetch<any[]>("/api/crud/transactions?cost_scope=shared&transaction_type=cost&limit=1000"),apiFetch<any[]>("/api/crud/allocations?limit=2000")]);setTransactions(t.filter(x=>!x.archived));setAllocations(a);}finally{setLoading(false);}}; useEffect(()=>{void load();},[]);
  const projectMap=useMemo(()=>new Map(lookups.projects.map(p=>[p.id,p.name])),[lookups.projects]); const catMap=useMemo(()=>new Map(lookups.categories.map(c=>[c.id,c.name])),[lookups.categories]);
  const total=moneyToCents(value); const preview=useMemo(()=>{if(!selected.length)return[]; if(method==="equal"){const base=Math.floor(total/selected.length);let remainder=total-base*selected.length;return selected.map((id,i)=>({project_id:id,amount:base+(remainder-->0?1:0)}));} return selected.map(id=>({project_id:id,amount:moneyToCents(manual[id]||"0")}));},[selected,method,total,manual]); const previewSum=preview.reduce((s,x)=>s+x.amount,0);
  const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
  const save=async()=>{if(!description.trim()||total<=0||!selected.length){setError("Informe descrição, valor e projetos do rateio.");return;} if(previewSum!==total){setError(`O rateio soma ${formatMoney(previewSum)}, mas o custo é ${formatMoney(total)}.`);return;} setSaving(true);setError("");try{await apiFetch("/api/shared-costs",{method:"POST",body:JSON.stringify({transaction_date:date,competence_month:`${month}-01`,category_id:categoryId||null,description,gross_amount_cents:total,unit_amount_cents:total,quantity:1,fee_amount_cents:0,status:"paid",provider:provider||null,allocations:preview.map(x=>({project_id:x.project_id,allocated_amount_cents:x.amount,allocation_method:method,percentage:method==="equal"?100/selected.length:null}))})});setOpen(false);setDescription("");setValue("");setSelected([]);setManual({});await load();}catch(e){setError(e instanceof Error?e.message:"Erro ao salvar.");}finally{setSaving(false);}};
  const markPaid=async(id:string)=>{await crudUpdate("transactions",id,{status:"paid",realized_at:todayInSaoPaulo()});await load();};
  const remove=async(id:string)=>{if(!confirm("Arquivar este custo compartilhado? As alocações deixarão de entrar nos cálculos."))return;await crudDelete("transactions",id);await load();};
  return <><PageHeader title="Custos compartilhados" description="Uma despesa real, distribuída gerencialmente entre projetos sem duplicar o custo no consolidado." actions={<Button onClick={()=>setOpen(true)}><Plus size={15}/> Novo custo compartilhado</Button>}/>
  <div className="note" style={{marginBottom:14}}><strong>Regra:</strong> o valor original é contabilizado uma única vez na holding. As alocações servem para reduzir o lucro gerencial de cada projeto participante.</div>
  {loading?<LoadingBlock lines={6}/>:<section className="panel table-wrap">{transactions.length===0?<EmptyState title="Nenhum custo compartilhado" description="Cadastre Vercel, AWS ou outra despesa usada por múltiplos projetos."/>:<table><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Provedor</th><th>Status</th><th>Rateio</th><th className="numeric">Valor</th><th></th></tr></thead><tbody>{transactions.map(t=>{const alloc=allocations.filter(a=>a.transaction_id===t.id);return <tr key={t.id}><td>{formatDate(t.transaction_date)}</td><td><strong>{t.description}</strong>{t.source==="recurrence"&&<div className="muted">Gerado por recorrência</div>}</td><td>{catMap.get(t.category_id)||"—"}</td><td>{t.provider||"—"}</td><td>{t.status==="paid"?"Pago":t.status==="planned"?"Previsto":t.status==="overdue"?"Atrasado":t.status}</td><td>{alloc.length?alloc.map(a=>`${projectMap.get(a.project_id)||"Projeto"}: ${formatMoney(a.allocated_amount_cents)}`).join(" · "):"Sem rateio"}</td><td className="numeric"><strong>{formatMoney(Number(t.gross_amount_cents)+Number(t.fee_amount_cents))}</strong></td><td><div className="inline-actions">{t.status!=="paid"&&t.status!=="cancelled"&&<button className="icon-button" title="Marcar como pago" onClick={()=>void markPaid(t.id)}><Check size={14}/></button>}<button className="icon-button" title="Arquivar" onClick={()=>remove(t.id)}><Trash2 size={14}/></button></div></td></tr>})}</tbody></table>}</section>}
  <Modal open={open} onClose={()=>setOpen(false)} title="Novo custo compartilhado" width="760px">{error&&<div className="error-box" style={{marginBottom:14}}>{error}</div>}<div className="form-grid"><div className="field"><label>Data</label><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>Competência</label><input className="input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div><div className="field full"><label>Descrição</label><input className="input" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: Vercel Pro"/></div><div className="field"><label>Categoria</label><select className="select" value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Sem categoria</option>{lookups.categories.filter(c=>c.applies_to!=="revenue").map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Provedor</label><input className="input" value={provider} onChange={e=>setProvider(e.target.value)} placeholder="Vercel, AWS..."/></div><div className="field"><label>Valor total</label><input className="input" value={value} onChange={e=>setValue(e.target.value)} placeholder="0,00" inputMode="decimal"/></div><div className="field"><label>Método</label><select className="select" value={method} onChange={e=>setMethod(e.target.value as any)}><option value="equal">Divisão igual</option><option value="manual">Valor manual por projeto</option></select></div><div className="field full"><label>Projetos participantes</label><div className="panel" style={{padding:10,display:"grid",gap:7}}>{lookups.projects.filter(p=>p.status==="active").map(p=><label key={p.id} style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)}/><span style={{flex:1}}>{p.name}</span>{selected.includes(p.id)&&method==="manual"&&<input className="input" style={{width:130}} value={manual[p.id]||""} onChange={e=>setManual(m=>({...m,[p.id]:e.target.value}))} placeholder="0,00"/>}{selected.includes(p.id)&&method==="equal"&&<strong>{formatMoney(preview.find(x=>x.project_id===p.id)?.amount||0)}</strong>}</label>)}</div></div><div className="field full"><div className={previewSum===total&&total>0?"success-box":"note"}><Split size={15} style={{verticalAlign:"-2px",marginRight:6}}/>Rateado: <strong>{formatMoney(previewSum)}</strong> de <strong>{formatMoney(total)}</strong></div></div></div><div className="form-actions"><Button variant="secondary" onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?"Salvando...":"Salvar e ratear"}</Button></div></Modal></>;
}
