"use client";
import { useEffect, useState } from "react";
import { Plus, Pencil } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { Badge } from "@/components/ui/badge";
import { LoadingBlock } from "@/components/ui/loading";
import { EmptyState } from "@/components/ui/empty-state";
import { apiFetch, crudCreate, crudUpdate } from "@/lib/client-api";
import { useLookups } from "@/lib/use-lookups";
import { formatMoney, moneyToCents } from "@/lib/money";
import { currentCompetence } from "@/lib/date";

function pct(actual:number,target:number){return target?Math.round(actual/target*100):0}

export default function GoalsPage(){
 const lookups=useLookups();const[month,setMonth]=useState(currentCompetence().slice(0,7));const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[modal,setModal]=useState(false),[editing,setEditing]=useState<any>(null);const[scope,setScope]=useState("project"),[projectId,setProjectId]=useState(""),[clients,setClients]=useState("0"),[setup,setSetup]=useState("0"),[recurring,setRecurring]=useState("0"),[total,setTotal]=useState(""),[notes,setNotes]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{setData(await apiFetch<any>(`/api/goals-summary?month=${month}`))}finally{setLoading(false)}};useEffect(()=>{void load()},[month]);
 function openNew(){setEditing(null);setScope("project");setProjectId(lookups.projects[0]?.id||"");setClients("0");setSetup("0");setRecurring("0");setTotal("");setNotes("");setError("");setModal(true)}
 function openEdit(g:any){setEditing(g);setScope(g.scope_type);setProjectId(g.project_id||"");setClients(String(g.target_clients));setSetup((g.target_setup_revenue_cents/100).toFixed(2).replace(".",","));setRecurring((g.target_recurring_revenue_cents/100).toFixed(2).replace(".",","));setTotal((g.target_total_revenue_cents/100).toFixed(2).replace(".",","));setNotes(g.notes||"");setError("");setModal(true)}
 const save=async()=>{if(scope==="project"&&!projectId){setError("Selecione um projeto.");return}setSaving(true);setError("");const setupC=moneyToCents(setup),recC=moneyToCents(recurring),totalC=total.trim()?moneyToCents(total):setupC+recC;const payload={scope_type:scope,project_id:scope==="project"?projectId:null,competence_month:`${month}-01`,target_clients:Number(clients)||0,target_setup_revenue_cents:setupC,target_recurring_revenue_cents:recC,target_total_revenue_cents:totalC,notes:notes||null};try{editing?await crudUpdate("goals",editing.id,payload):await crudCreate("goals",payload);setModal(false);await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar. Verifique se já existe meta para esse escopo/mês.")}finally{setSaving(false)}};
 const rows=data?.rows||[];
 return <><PageHeader title="Metas" description="Planejado × realizado por projeto, SaaS e projetos de cliente da Prodexy." actions={<Button onClick={openNew}><Plus size={15}/> Nova meta</Button>}/><div className="filter-bar"><div className="field"><label>Competência</label><input className="input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div></div>{loading?<LoadingBlock lines={7}/>:<section className="panel table-wrap">{rows.length===0?<EmptyState title="Nenhuma meta nesta competência" description="Defina metas de clientes e receita para acompanhar o realizado."/>:<table><thead><tr><th>Escopo</th><th className="numeric">Clientes</th><th>Progresso clientes</th><th className="numeric">Implantação</th><th className="numeric">Recorrente</th><th className="numeric">Receita total</th><th>Progresso receita</th><th></th></tr></thead><tbody>{rows.map((g:any)=>{const clientPct=pct(g.actual_clients,g.target_clients),revenuePct=pct(g.actual_total_revenue_cents,g.target_total_revenue_cents);return <tr key={g.id}><td><strong>{g.label}</strong><div><Badge tone={g.scope_type==="project"?"purple":"neutral"}>{g.scope_type==="project"?"Projeto":g.scope_type==="client_projects"?"Projetos de cliente":"Holding"}</Badge></div></td><td className="numeric"><strong>{g.actual_clients} / {g.target_clients}</strong></td><td style={{minWidth:140}}><div className="progress"><span style={{width:`${Math.min(100,clientPct)}%`}}/></div><small className="muted">{clientPct}% · faltam {Math.max(0,g.target_clients-g.actual_clients)}</small></td><td className="numeric"><div>{formatMoney(g.actual_setup_revenue_cents)}</div><small className="muted">meta {formatMoney(g.target_setup_revenue_cents)}</small></td><td className="numeric"><div>{formatMoney(g.actual_recurring_revenue_cents)}</div><small className="muted">meta {formatMoney(g.target_recurring_revenue_cents)}</small></td><td className="numeric"><strong>{formatMoney(g.actual_total_revenue_cents)}</strong><div className="muted">meta {formatMoney(g.target_total_revenue_cents)}</div></td><td style={{minWidth:140}}><div className="progress"><span style={{width:`${Math.min(100,revenuePct)}%`}}/></div><small className="muted">{revenuePct}% · faltam {formatMoney(Math.max(0,g.target_total_revenue_cents-g.actual_total_revenue_cents))}</small></td><td><button className="icon-button" onClick={()=>openEdit(g)}><Pencil size={14}/></button></td></tr>})}</tbody></table>}</section>}
 <Modal open={modal} onClose={()=>setModal(false)} title={editing?"Editar meta":"Nova meta"}>{error&&<div className="error-box" style={{marginBottom:14}}>{error}</div>}<div className="form-grid"><div className="field"><label>Escopo</label><select className="select" value={scope} onChange={e=>setScope(e.target.value)} disabled={!!editing}><option value="project">Projeto</option><option value="client_projects">Projetos de cliente (Prodexy)</option><option value="holding">Holding consolidada</option></select></div>{scope==="project"&&<div className="field"><label>Projeto</label><select className="select" value={projectId} onChange={e=>setProjectId(e.target.value)} disabled={!!editing}><option value="">Selecione</option>{lookups.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>}<div className="field"><label>Meta de clientes</label><input className="input" type="number" min="0" value={clients} onChange={e=>setClients(e.target.value)}/></div><div className="field"><label>Implantação</label><input className="input" value={setup} onChange={e=>setSetup(e.target.value)}/></div><div className="field"><label>Receita recorrente</label><input className="input" value={recurring} onChange={e=>setRecurring(e.target.value)}/></div><div className="field"><label>Receita total</label><input className="input" value={total} onChange={e=>setTotal(e.target.value)} placeholder="Vazio = implantação + recorrente"/></div><div className="field full"><label>Observação</label><textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)}/></div></div><div className="form-actions"><Button variant="secondary" onClick={()=>setModal(false)}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?"Salvando...":"Salvar meta"}</Button></div></Modal></>;
}
