"use client";
import { useEffect, useMemo, useState } from "react";
import { LockKeyhole, RotateCcw } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { LoadingBlock } from "@/components/ui/loading";
import { apiFetch } from "@/lib/client-api";
import { useLookups } from "@/lib/use-lookups";
import { formatMoney, formatPercent } from "@/lib/money";
import { currentCompetence, formatDateTime } from "@/lib/date";

export default function ClosingsPage(){
 const lookups=useLookups();const[month,setMonth]=useState(currentCompetence().slice(0,7));const[dashboard,setDashboard]=useState<any>(null);const[closings,setClosings]=useState<any[]>([]);const[distributions,setDistributions]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{const[d,c,dist]=await Promise.all([apiFetch<any>(`/api/dashboard?month=${month}`),apiFetch<any[]>(`/api/crud/closings?competence_month=${month}-01&limit=500`),apiFetch<any[]>("/api/crud/distributions?limit=2000")]);setDashboard(d);setClosings(c);setDistributions(dist);}finally{setLoading(false)}};useEffect(()=>{void load()},[month]);
 const closingMap=useMemo(()=>new Map(closings.map(c=>[c.project_id,c])),[closings]);
 const act=async(action:"close"|"reopen",projectId:string,closingId?:string)=>{if(action==="close"&&!confirm("Fechar esta competência? O sistema criará um snapshot e as distribuições de lucro."))return;if(action==="reopen"&&!confirm("Reabrir o fechamento? Os lançamentos poderão ser corrigidos e o mês recalculado ao fechar novamente."))return;setBusy(projectId);setError("");try{await apiFetch("/api/closings",{method:"POST",body:JSON.stringify(action==="close"?{action,project_id:projectId,competence_month:`${month}-01`}:{action,closing_id:closingId})});await load();}catch(e){setError(e instanceof Error?e.message:"Falha no fechamento.");}finally{setBusy(null)}};
 return <><PageHeader title="Fechamentos" description="Congela o resultado do projeto e a participação societária usada naquele mês." actions={<div className="field"><label>Competência</label><input type="month" className="input" value={month} onChange={e=>setMonth(e.target.value)}/></div>}/>{error&&<div className="error-box" style={{marginBottom:14}}>{error}</div>}{loading?<LoadingBlock lines={7}/>:<section className="panel table-wrap"><table><thead><tr><th>Projeto</th><th className="numeric">Receita líquida</th><th className="numeric">Custos</th><th className="numeric">Lucro</th><th className="numeric">Margem</th><th>Distribuição</th><th>Status</th><th></th></tr></thead><tbody>{(dashboard?.project_summaries||[]).map((p:any)=>{const c=closingMap.get(p.project_id);const dist=c?distributions.filter(d=>d.closing_id===c.id):[];return <tr key={p.project_id}><td><strong>{p.project_name}</strong></td><td className="numeric">{formatMoney(p.revenue_net_cents)}</td><td className="numeric">{formatMoney(p.direct_costs_cents+p.shared_costs_cents)}</td><td className={`numeric ${p.profit_cents<0?"negative":""}`}><strong>{formatMoney(p.profit_cents)}</strong></td><td className="numeric">{p.margin_percentage==null?"—":formatPercent(p.margin_percentage)}</td><td>{c?<div style={{display:"grid",gap:2}}>{dist.map(d=><small key={d.id}>{d.partner_name_snapshot}: {formatMoney(d.amount_cents)}</small>)}{dist.length===0&&<small className="muted">Sem lucro distribuível</small>}</div>:<span className="muted">Será calculada ao fechar</span>}</td><td>{c?.status==="closed"?<><Badge tone="positive">Fechado</Badge><div className="muted" style={{fontSize:10,marginTop:3}}>{formatDateTime(c.closed_at)}</div></>:c?.status==="reopened"?<Badge tone="warning">Reaberto</Badge>:<Badge>Aberto</Badge>}</td><td>{c?.status==="closed"?<Button variant="secondary" disabled={busy===p.project_id} onClick={()=>act("reopen",p.project_id,c.id)}><RotateCcw size={14}/> Reabrir</Button>:<Button disabled={busy===p.project_id} onClick={()=>act("close",p.project_id)}><LockKeyhole size={14}/> Fechar mês</Button>}</td></tr>})}</tbody></table></section>}<div className="note" style={{marginTop:14}}>Se um projeto não tiver sócios cadastrados, o sistema considera 100% do lucro como pertencente à Prodexy Labs. Se houver sócios cadastrados, a soma das participações ativas precisa ser 100% para permitir o fechamento.</div></>;
}
