"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Clock3, Columns3, List, Plus, Play, RefreshCw, Square, TimerReset } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { LoadingBlock } from "@/components/ui/loading";
import { EmptyState } from "@/components/ui/empty-state";
import { apiFetch, crudCreate, crudUpdate } from "@/lib/client-api";
import { useLookups } from "@/lib/use-lookups";
import { formatDateTime, todayInSaoPaulo } from "@/lib/date";

const statusLabels:any={inbox:"Caixa de entrada",backlog:"Backlog",planned:"Planejada",in_progress:"Em andamento",waiting:"Aguardando",done:"Concluída",cancelled:"Cancelada"};
const priorityLabels:any={critical:"Crítica",high:"Alta",medium:"Média",low:"Baixa"};
function priorityTone(p:string){return p==="critical"?"negative":p==="high"?"warning":p==="medium"?"info":"neutral"}

export default function TasksPage(){
 const deepLinkHandled=useRef(false);const lookups=useLookups();const[tasks,setTasks]=useState<any[]>([]),[timeEntries,setTimeEntries]=useState<any[]>([]),[activeTimer,setActiveTimer]=useState<any>(null),[loading,setLoading]=useState(true);const[view,setView]=useState<"list"|"kanban">("list"),[project,setProject]=useState("all"),[status,setStatus]=useState("open"),[priority,setPriority]=useState("all"),[search,setSearch]=useState("");
 const[modal,setModal]=useState(false),[editing,setEditing]=useState<any>(null),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[taskProject,setTaskProject]=useState(""),[clientId,setClientId]=useState(""),[categoryId,setCategoryId]=useState(""),[taskPriority,setTaskPriority]=useState("medium"),[taskStatus,setTaskStatus]=useState("inbox"),[dueAt,setDueAt]=useState(""),[estimate,setEstimate]=useState(""),[nextAction,setNextAction]=useState(""),[origin,setOrigin]=useState(""),[notes,setNotes]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const[recurringOpen,setRecurringOpen]=useState(false),[recTitle,setRecTitle]=useState(""),[recFreq,setRecFreq]=useState("monthly"),[recNext,setRecNext]=useState(todayInSaoPaulo()),[recProject,setRecProject]=useState("");const[manualOpen,setManualOpen]=useState(false),[manualTask,setManualTask]=useState<any>(null),[manualMinutes,setManualMinutes]=useState(""),[manualNotes,setManualNotes]=useState("");
 const load=async()=>{setLoading(true);try{const[t,e,timer]=await Promise.all([apiFetch<any[]>("/api/crud/tasks?limit=2000"),apiFetch<any[]>("/api/crud/time-entries?limit=4000"),apiFetch<any>("/api/timer")]);setTasks(t.filter(x=>!x.archived));setTimeEntries(e);setActiveTimer(timer);}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 useEffect(()=>{const p=new URLSearchParams(window.location.search);const pid=p.get("projeto");if(pid)setProject(pid);if(p.get("novo"))openNew(pid&&pid!=="holding"?pid:undefined);},[]);useEffect(()=>{if(deepLinkHandled.current||!tasks.length)return;const tid=new URLSearchParams(window.location.search).get("tarefa");if(tid){const target=tasks.find(t=>t.id===tid);if(target)openEdit(target)}deepLinkHandled.current=true},[tasks]);
 const projectMap=useMemo(()=>new Map(lookups.projects.map(p=>[p.id,p.name])),[lookups.projects]),clientMap=useMemo(()=>new Map(lookups.clients.map(c=>[c.id,c.name])),[lookups.clients]),catMap=useMemo(()=>new Map(lookups.taskCategories.map(c=>[c.id,c.name])),[lookups.taskCategories]);
 const timeByTask=useMemo(()=>{const m=new Map<string,number>();for(const e of timeEntries){if(e.task_id)m.set(e.task_id,(m.get(e.task_id)||0)+Number(e.duration_minutes||0))}return m},[timeEntries]);
 const filtered=tasks.filter(t=>(project==="all"||t.project_id===project||(project==="holding"&&!t.project_id))&&(priority==="all"||t.priority===priority)&&(status==="all"||status==="open"&&!["done","cancelled"].includes(t.status)||t.status===status)&&(!search||`${t.title} ${t.description||""} ${t.next_action||""}`.toLowerCase().includes(search.toLowerCase())));
 function openNew(defaultProjectId?:string){setEditing(null);setTitle("");setDescription("");setTaskProject(defaultProjectId??(project!=="all"&&project!=="holding"?project:""));setClientId("");setCategoryId("");setTaskPriority("medium");setTaskStatus("inbox");setDueAt("");setEstimate("");setNextAction("");setOrigin("");setNotes("");setError("");setModal(true)}
 function openEdit(t:any){setEditing(t);setTitle(t.title);setDescription(t.description||"");setTaskProject(t.project_id||"");setClientId(t.client_id||"");setCategoryId(t.category_id||"");setTaskPriority(t.priority);setTaskStatus(t.status);setDueAt(t.due_at?new Date(t.due_at).toISOString().slice(0,16):"");setEstimate(t.estimated_minutes?String(t.estimated_minutes):"");setNextAction(t.next_action||"");setOrigin(t.origin||"");setNotes(t.notes||"");setError("");setModal(true)}
 const save=async()=>{if(!title.trim()){setError("Título obrigatório.");return}setSaving(true);setError("");const payload={title:title.trim(),description:description||null,project_id:taskProject||null,client_id:clientId||null,category_id:categoryId||null,priority:taskPriority,status:taskStatus,due_at:dueAt?new Date(dueAt).toISOString():null,estimated_minutes:estimate?Number(estimate):null,next_action:nextAction||null,origin:origin||null,notes:notes||null,completed_at:taskStatus==="done"?new Date().toISOString():null};try{editing?await crudUpdate("tasks",editing.id,payload):await crudCreate("tasks",payload);setModal(false);await load()}catch(e){setError(e instanceof Error?e.message:"Erro ao salvar.")}finally{setSaving(false)}};
 const quickStatus=async(t:any,newStatus:string)=>{await crudUpdate("tasks",t.id,{status:newStatus,completed_at:newStatus==="done"?new Date().toISOString():null});await load()};
 const timer=async(action:"start"|"stop",taskId?:string)=>{await apiFetch("/api/timer",{method:"POST",body:JSON.stringify({action,task_id:taskId})});await load()};
 const createRecurring=async()=>{if(!recTitle.trim())return;await crudCreate("recurring-tasks",{title:recTitle,project_id:recProject||null,priority:"medium",frequency:recFreq,interval_count:1,next_run_date:recNext,active:true});setRecurringOpen(false);setRecTitle("")};const saveManualTime=async()=>{const minutes=Number(manualMinutes);if(!manualTask||!Number.isFinite(minutes)||minutes<=0)return;await apiFetch("/api/timer",{method:"POST",body:JSON.stringify({action:"manual",task_id:manualTask.id,minutes,notes:manualNotes||undefined})});setManualOpen(false);setManualTask(null);setManualMinutes("");setManualNotes("");await load()};
 const runRecurrences=async()=>{await apiFetch("/api/recurrences/run",{method:"POST"});await load()};
 const kanbanStatuses=["inbox","backlog","planned","in_progress","waiting","done"];
 return <><PageHeader title="Demandas" description="Pedidos de clientes, bugs, melhorias, reuniões, ideias e atividades internas em um só lugar." actions={<><Button variant="secondary" onClick={()=>setRecurringOpen(true)}><RefreshCw size={14}/> Recorrência</Button><Button onClick={()=>openNew()}><Plus size={15}/> Nova demanda</Button></>}/>
 {activeTimer&&<div className="success-box" style={{marginBottom:14,display:"flex",alignItems:"center",gap:10}}><Clock3 size={15}/><span style={{flex:1}}>Cronômetro ativo desde {formatDateTime(activeTimer.started_at)}.</span><Button variant="danger" onClick={()=>timer("stop")}><Square size={14}/> Parar</Button></div>}
 <div className="filter-bar"><div className="field"><label>Projeto</label><select className="select" value={project} onChange={e=>setProject(e.target.value)}><option value="all">Todos</option><option value="holding">Prodexy / Interno</option>{lookups.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Status</label><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Abertas</option><option value="all">Todos</option>{Object.entries(statusLabels).map(([k,v])=><option value={k} key={k}>{String(v)}</option>)}</select></div><div className="field"><label>Prioridade</label><select className="select" value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">Todas</option>{Object.entries(priorityLabels).map(([k,v])=><option value={k} key={k}>{String(v)}</option>)}</select></div><div className="field grow"><label>Buscar</label><input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Título, descrição, próxima ação..."/></div><div className="inline-actions"><button className={`icon-button ${view==="list"?"active":""}`} onClick={()=>setView("list")}><List size={15}/></button><button className={`icon-button ${view==="kanban"?"active":""}`} onClick={()=>setView("kanban")}><Columns3 size={15}/></button></div></div>
 {loading?<LoadingBlock lines={8}/>:view==="list"?<section className="panel table-wrap">{filtered.length===0?<EmptyState title="Nenhuma demanda encontrada"/>:<table><thead><tr><th>Demanda</th><th>Projeto</th><th>Prioridade</th><th>Status</th><th>Prazo</th><th className="numeric">Estimado</th><th className="numeric">Realizado</th><th></th></tr></thead><tbody>{filtered.map(t=>{const overdue=t.due_at&&new Date(t.due_at)<new Date()&&!["done","cancelled"].includes(t.status);return <tr key={t.id}><td><button onClick={()=>openEdit(t)} className="table-link" style={{border:0,background:"transparent",padding:0,textAlign:"left"}}>{t.title}</button>{t.next_action&&<div className="muted">Próxima: {t.next_action}</div>}</td><td>{t.project_id?projectMap.get(t.project_id)||"—":"Prodexy Labs"}{t.client_id&&<div className="muted">{clientMap.get(t.client_id)||"Cliente"}</div>}</td><td><Badge tone={priorityTone(t.priority) as any}>{priorityLabels[t.priority]}</Badge></td><td><select className="select" style={{height:30,minWidth:125}} value={t.status} onChange={e=>quickStatus(t,e.target.value)}>{Object.entries(statusLabels).map(([k,v])=><option value={k} key={k}>{String(v)}</option>)}</select></td><td className={overdue?"negative":""}>{formatDateTime(t.due_at)}</td><td className="numeric">{t.estimated_minutes?`${t.estimated_minutes} min`:"—"}</td><td className="numeric">{timeByTask.get(t.id)?`${timeByTask.get(t.id)} min`:"—"}</td><td><div className="inline-actions">{activeTimer?.task_id===t.id?<Button variant="danger" onClick={()=>timer("stop")}><Square size={13}/></Button>:<Button variant="secondary" onClick={()=>timer("start",t.id)}><Play size={13}/></Button>}<button className="icon-button" title="Registrar tempo manualmente" onClick={()=>{setManualTask(t);setManualMinutes("");setManualNotes("");setManualOpen(true)}}><TimerReset size={14}/></button></div></td></tr>})}</tbody></table>}</section>:<div style={{display:"grid",gridTemplateColumns:"repeat(6,minmax(220px,1fr))",gap:10,overflowX:"auto",paddingBottom:8}}>{kanbanStatuses.map(s=><section className="panel" key={s} style={{minWidth:220}}><div className="panel-header"><h3>{statusLabels[s]}</h3><Badge>{filtered.filter(t=>t.status===s).length}</Badge></div><div className="panel-body" style={{display:"grid",gap:8}}>{filtered.filter(t=>t.status===s).map(t=><button key={t.id} onClick={()=>openEdit(t)} style={{textAlign:"left",border:"1px solid var(--border)",background:"white",borderRadius:8,padding:10}}><strong>{t.title}</strong><div className="muted" style={{fontSize:10,marginTop:5}}>{t.project_id?projectMap.get(t.project_id):"Prodexy Labs"}</div><div style={{marginTop:7}}><Badge tone={priorityTone(t.priority) as any}>{priorityLabels[t.priority]}</Badge></div></button>)}</div></section>)}</div>}
 <Modal open={modal} onClose={()=>setModal(false)} title={editing?"Editar demanda":"Nova demanda"} width="760px">{error&&<div className="error-box" style={{marginBottom:14}}>{error}</div>}<div className="form-grid"><div className="field full"><label>Título</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)} autoFocus/></div><div className="field full"><label>Descrição</label><textarea className="textarea" value={description} onChange={e=>setDescription(e.target.value)}/></div><div className="field"><label>Projeto</label><select className="select" value={taskProject} onChange={e=>setTaskProject(e.target.value)}><option value="">Prodexy / Interno</option>{lookups.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Cliente</label><select className="select" value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Sem cliente</option>{lookups.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Tipo</label><select className="select" value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Sem tipo</option>{lookups.taskCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Prioridade</label><select className="select" value={taskPriority} onChange={e=>setTaskPriority(e.target.value)}>{Object.entries(priorityLabels).map(([k,v])=><option value={k} key={k}>{String(v)}</option>)}</select></div><div className="field"><label>Status</label><select className="select" value={taskStatus} onChange={e=>setTaskStatus(e.target.value)}>{Object.entries(statusLabels).map(([k,v])=><option value={k} key={k}>{String(v)}</option>)}</select></div><div className="field"><label>Prazo</label><input className="input" type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></div><div className="field"><label>Estimativa (min)</label><input className="input" type="number" value={estimate} onChange={e=>setEstimate(e.target.value)}/></div><div className="field"><label>Origem</label><input className="input" value={origin} onChange={e=>setOrigin(e.target.value)} placeholder="WhatsApp, reunião..."/></div><div className="field full"><label>Próxima ação</label><input className="input" value={nextAction} onChange={e=>setNextAction(e.target.value)}/></div><div className="field full"><label>Observações</label><textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)}/></div></div><div className="form-actions"><Button variant="secondary" onClick={()=>setModal(false)}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?"Salvando...":"Salvar demanda"}</Button></div></Modal>
 <Modal open={manualOpen} onClose={()=>setManualOpen(false)} title={`Registrar tempo${manualTask?` — ${manualTask.title}`:""}`}><div className="form-grid"><div className="field"><label>Minutos</label><input className="input" type="number" min="1" value={manualMinutes} onChange={e=>setManualMinutes(e.target.value)} autoFocus/></div><div className="field full"><label>Observação</label><input className="input" value={manualNotes} onChange={e=>setManualNotes(e.target.value)} placeholder="Opcional"/></div></div><div className="form-actions"><Button variant="secondary" onClick={()=>setManualOpen(false)}>Cancelar</Button><Button onClick={saveManualTime}>Registrar</Button></div></Modal>
 <Modal open={recurringOpen} onClose={()=>setRecurringOpen(false)} title="Nova demanda recorrente"><div className="form-grid"><div className="field full"><label>Título</label><input className="input" value={recTitle} onChange={e=>setRecTitle(e.target.value)}/></div><div className="field"><label>Projeto</label><select className="select" value={recProject} onChange={e=>setRecProject(e.target.value)}><option value="">Prodexy / Interno</option>{lookups.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Periodicidade</label><select className="select" value={recFreq} onChange={e=>setRecFreq(e.target.value)}><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option></select></div><div className="field"><label>Próxima geração</label><input className="input" type="date" value={recNext} onChange={e=>setRecNext(e.target.value)}/></div></div><div className="form-actions"><Button variant="ghost" onClick={runRecurrences}>Gerar vencidas agora</Button><Button variant="secondary" onClick={()=>setRecurringOpen(false)}>Cancelar</Button><Button onClick={createRecurring}>Salvar recorrência</Button></div></Modal>
 </>;
}
