"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Plus, FolderKanban } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { LoadingBlock } from "@/components/ui/loading";
import { EmptyState } from "@/components/ui/empty-state";
import { apiFetch, crudCreate } from "@/lib/client-api";
import { formatMoney } from "@/lib/money";
import { currentCompetence } from "@/lib/date";

export default function ProjectsPage(){
 const[projects,setProjects]=useState<any[]>([]),[dashboard,setDashboard]=useState<any>(null),[tasks,setTasks]=useState<any[]>([]);const[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[filter,setFilter]=useState("all");
 const[name,setName]=useState(""),[type,setType]=useState("client"),[description,setDescription]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{const[p,d,t]=await Promise.all([apiFetch<any[]>("/api/crud/projects?limit=500"),apiFetch<any>(`/api/dashboard?month=${currentCompetence().slice(0,7)}`),apiFetch<any[]>("/api/crud/tasks?limit=1000")]);setProjects(p);setDashboard(d);setTasks(t);}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const summaryMap=useMemo(()=>new Map((dashboard?.project_summaries||[]).map((x:any)=>[x.project_id,x])),[dashboard]);
 const filtered=projects.filter(p=>p.status!=="archived"&&(filter==="all"||p.project_type===filter||p.status===filter));
 const save=async()=>{if(!name.trim()){setError("Informe o nome do projeto.");return}setSaving(true);setError("");try{await crudCreate("projects",{name:name.trim(),project_type:type,status:"active",description:description||null});setOpen(false);setName("");setDescription("");await load()}catch(e){setError(e instanceof Error?e.message:"Erro ao criar projeto.")}finally{setSaving(false)}};
 return <><PageHeader title="Projetos" description="Cada projeto funciona como uma unidade operacional e econômica, sem exigir estruturas de banco específicas." actions={<Button onClick={()=>setOpen(true)}><Plus size={15}/> Novo projeto</Button>}/><div className="filter-bar"><div className="field"><label>Visualizar</label><select className="select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos ativos</option><option value="client">Projetos de cliente</option><option value="saas">SaaS</option><option value="internal">Internos</option><option value="paused">Pausados</option><option value="closed">Encerrados</option></select></div></div>
 {loading?<LoadingBlock lines={7}/>:<section className="panel table-wrap">{filtered.length===0?<EmptyState title="Nenhum projeto"/>:<table><thead><tr><th>Projeto</th><th>Tipo</th><th>Status</th><th className="numeric">Receita líquida</th><th className="numeric">Lucro</th><th className="numeric">Parte Prodexy</th><th className="numeric">Demandas abertas</th><th className="numeric">Atrasadas</th></tr></thead><tbody>{filtered.map(p=>{const s:any=summaryMap.get(p.id)||{};const pt=tasks.filter(t=>t.project_id===p.id&&!t.archived&&!["done","cancelled"].includes(t.status));const overdue=pt.filter(t=>t.due_at&&new Date(t.due_at)<new Date()).length;return <tr key={p.id}><td><Link href={`/projetos/${p.id}`} className="table-link">{p.name}</Link>{p.description&&<div className="muted">{p.description}</div>}</td><td><Badge tone={p.project_type==="saas"?"purple":p.project_type==="client"?"info":"neutral"}>{p.project_type==="saas"?"SaaS":p.project_type==="client"?"Cliente":"Interno"}</Badge></td><td><Badge tone={p.status==="active"?"positive":p.status==="paused"?"warning":"neutral"}>{p.status==="active"?"Ativo":p.status==="paused"?"Pausado":"Encerrado"}</Badge></td><td className="numeric">{formatMoney(s.revenue_net_cents||0)}</td><td className={`numeric ${(s.profit_cents||0)<0?"negative":""}`}>{formatMoney(s.profit_cents||0)}</td><td className="numeric"><strong>{formatMoney(s.prodexy_share_cents||0)}</strong></td><td className="numeric">{pt.length}</td><td className={`numeric ${overdue?"negative":""}`}>{overdue}</td></tr>})}</tbody></table>}</section>}
 <Modal open={open} onClose={()=>setOpen(false)} title="Novo projeto"><>{error&&<div className="error-box" style={{marginBottom:14}}>{error}</div>}<div className="form-grid"><div className="field full"><label>Nome</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do projeto"/></div><div className="field"><label>Tipo</label><select className="select" value={type} onChange={e=>setType(e.target.value)}><option value="client">Projeto de cliente</option><option value="saas">SaaS</option><option value="internal">Interno</option></select></div><div className="field full"><label>Descrição</label><textarea className="textarea" value={description} onChange={e=>setDescription(e.target.value)}/></div></div><div className="form-actions"><Button variant="secondary" onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?"Criando...":"Criar projeto"}</Button></div></></Modal></>;
}
