"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Plus, Play, Pencil } from "lucide-react";
import { PageHeader } from "./ui/page-header";
import { KpiCard } from "./ui/kpi-card";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Modal } from "./ui/modal";
import { LoadingBlock } from "./ui/loading";
import { EmptyState } from "./ui/empty-state";
import { TransactionModal } from "./transaction-modal";
import { apiFetch, crudCreate, crudUpdate } from "@/lib/client-api";
import { useLookups } from "@/lib/use-lookups";
import { formatMoney, formatPercent, moneyToCents } from "@/lib/money";
import { currentCompetence, formatDate, formatDateTime, todayInSaoPaulo } from "@/lib/date";

const tabs=["Visão geral","Financeiro","Clientes","Demandas","Metas","Sócios","Tempo"];

export function ProjectDetail({projectId}:{projectId:string}){
 const lookups=useLookups();const[tab,setTab]=useState("Visão geral"),[loading,setLoading]=useState(true),[project,setProject]=useState<any>(null),[summary,setSummary]=useState<any>(null),[transactions,setTransactions]=useState<any[]>([]),[tasks,setTasks]=useState<any[]>([]),[relations,setRelations]=useState<any[]>([]),[goals,setGoals]=useState<any[]>([]),[projectPartners,setProjectPartners]=useState<any[]>([]),[timeEntries,setTimeEntries]=useState<any[]>([]),[plans,setPlans]=useState<any[]>([]),[subscriptions,setSubscriptions]=useState<any[]>([]);const[txOpen,setTxOpen]=useState(false);
 const[editProjectModal,setEditProjectModal]=useState(false),[projName,setProjName]=useState(""),[projType,setProjType]=useState("client"),[projStatus,setProjStatus]=useState("active"),[projDescription,setProjDescription]=useState(""),[primaryClient,setPrimaryClient]=useState("");const[clientModal,setClientModal]=useState(false),[selectedClient,setSelectedClient]=useState("");const[partnerModal,setPartnerModal]=useState(false),[partnerEditing,setPartnerEditing]=useState<any>(null),[partnerId,setPartnerId]=useState(""),[newPartnerName,setNewPartnerName]=useState(""),[pct,setPct]=useState(""),[partnerStart,setPartnerStart]=useState(currentCompetence()),[partnerEnd,setPartnerEnd]=useState(""),[partnerError,setPartnerError]=useState("");const[planModal,setPlanModal]=useState(false),[planName,setPlanName]=useState(""),[planValue,setPlanValue]=useState("");const[subModal,setSubModal]=useState(false),[subClient,setSubClient]=useState(""),[subPlan,setSubPlan]=useState(""),[subValue,setSubValue]=useState("");
 const month=currentCompetence().slice(0,7);
 const load=async()=>{setLoading(true);try{const[p,d,tx,t,rel,g,pp,te,pl,su]=await Promise.all([apiFetch<any[]>(`/api/crud/projects?id=${projectId}`),apiFetch<any>(`/api/dashboard?month=${month}`),apiFetch<any[]>(`/api/crud/transactions?project_id=${projectId}&limit=1000`),apiFetch<any[]>(`/api/crud/tasks?project_id=${projectId}&limit=1000`),apiFetch<any[]>(`/api/crud/project-clients?project_id=${projectId}&limit=1000`),apiFetch<any[]>(`/api/crud/goals?project_id=${projectId}&limit=1000`),apiFetch<any[]>(`/api/crud/project-partners?project_id=${projectId}&limit=1000`),apiFetch<any[]>(`/api/crud/time-entries?project_id=${projectId}&limit=2000`),apiFetch<any[]>(`/api/crud/plans?project_id=${projectId}&limit=500`),apiFetch<any[]>(`/api/crud/subscriptions?project_id=${projectId}&limit=1000`)]);const pr=p[0];setProject(pr);setSummary((d.project_summaries||[]).find((x:any)=>x.project_id===projectId)||null);setTransactions(tx.filter(x=>!x.archived));setTasks(t.filter(x=>!x.archived));setRelations(rel);setGoals(g);setProjectPartners(pp);setTimeEntries(te);setPlans(pl);setSubscriptions(su);}finally{setLoading(false)}};useEffect(()=>{void load()},[projectId]);
 const clientMap=useMemo(()=>new Map(lookups.clients.map(c=>[c.id,c])),[lookups.clients]),partnerMap=useMemo(()=>new Map(lookups.partners.map(p=>[p.id,p])),[lookups.partners]);
 const relatedClients=relations.map(r=>clientMap.get(r.client_id)).filter(Boolean);const openTasks=tasks.filter(t=>!["done","cancelled"].includes(t.status));const totalMinutes=timeEntries.reduce((s,e)=>s+Number(e.duration_minutes||0),0);const compositionDate=currentCompetence();const activeProjectPartners=projectPartners.filter(pp=>pp.active&&pp.start_date<=compositionDate&&(!pp.end_date||pp.end_date>=compositionDate));const holdingParticipation=activeProjectPartners.filter(pp=>(partnerMap.get(pp.partner_id) as any)?.partner_type==="holding").reduce((sum,pp)=>sum+Number(pp.participation_percentage||0),0);const externalParticipation=activeProjectPartners.filter(pp=>(partnerMap.get(pp.partner_id) as any)?.partner_type==="external").reduce((sum,pp)=>sum+Number(pp.participation_percentage||0),0);const participationTotal=holdingParticipation+externalParticipation;
 const openProjectEdit=()=>{setProjName(project.name||"");setProjType(project.project_type||"client");setProjStatus(project.status||"active");setProjDescription(project.description||"");setPrimaryClient(project.primary_client_id||"");setEditProjectModal(true)};const saveProject=async()=>{if(!projName.trim())return;await crudUpdate("projects",projectId,{name:projName.trim(),project_type:projType,status:projStatus,description:projDescription||null,primary_client_id:primaryClient||null});setEditProjectModal(false);await load();await lookups.refresh()};
 const addClient=async()=>{if(!selectedClient)return;await crudCreate("project-clients",{project_id:projectId,client_id:selectedClient,relationship_type:project?.project_type==="saas"?"subscriber":"client",active:true});if(project?.project_type==="client"&&!project?.primary_client_id)await crudUpdate("projects",projectId,{primary_client_id:selectedClient});setClientModal(false);setSelectedClient("");await load();await lookups.refresh()};
 const openNewPartner=()=>{setPartnerEditing(null);setPartnerId("");setNewPartnerName("");setPct("50");setPartnerStart(currentCompetence());setPartnerEnd("");setPartnerError("");setPartnerModal(true)};const openEditPartner=(pp:any)=>{setPartnerEditing(pp);setPartnerId(pp.partner_id);setNewPartnerName("");setPct(String(pp.participation_percentage).replace(".",","));setPartnerStart(pp.start_date||currentCompetence());setPartnerEnd(pp.end_date||"");setPartnerError("");setPartnerModal(true)};const savePartner=async()=>{const percentage=Number(pct.replace(",","."));if(!partnerId||!partnerStart){setPartnerError("Selecione o participante e informe o início da vigência.");return}if(!Number.isFinite(percentage)||percentage<=0||percentage>100){setPartnerError("A participação deve ser maior que 0% e menor ou igual a 100%.");return}if(partnerId==="new-external"&&!newPartnerName.trim()){setPartnerError("Informe o nome do novo sócio.");return}setPartnerError("");try{let selectedPartnerId=partnerId;if(partnerId==="new-external"){const created=await crudCreate<any>("partners",{name:newPartnerName.trim(),partner_type:"external",active:true});selectedPartnerId=created.id}const payload={project_id:projectId,partner_id:selectedPartnerId,participation_percentage:percentage,start_date:partnerStart,end_date:partnerEnd||null,active:true};partnerEditing?await crudUpdate("project-partners",partnerEditing.id,payload):await crudCreate("project-partners",payload);setPartnerModal(false);setPartnerEditing(null);setPartnerId("");setNewPartnerName("");setPct("");await load();await lookups.refresh()}catch(cause){setPartnerError(cause instanceof Error?cause.message:"Não foi possível salvar a participação.")}};
 const addPlan=async()=>{if(!planName||!planValue)return;await crudCreate("plans",{project_id:projectId,name:planName,monthly_amount_cents:moneyToCents(planValue),setup_fee_cents:0,active:true});setPlanModal(false);setPlanName("");setPlanValue("");await load()};
 const addSubscription=async()=>{if(!subClient||!subValue)return;const relation=relations.find(r=>r.client_id===subClient);if(!relation)await crudCreate("project-clients",{project_id:projectId,client_id:subClient,relationship_type:"subscriber",active:true});else if(!relation.active||relation.relationship_type!=="subscriber")await crudUpdate("project-clients",relation.id,{relationship_type:"subscriber",active:true});await crudCreate("subscriptions",{project_id:projectId,client_id:subClient,plan_id:subPlan||null,monthly_amount_cents:moneyToCents(subValue),status:"active",start_date:todayInSaoPaulo()});setSubModal(false);setSubClient("");setSubPlan("");setSubValue("");await load();await lookups.refresh()};
 const startTimer=async(id:string)=>{await apiFetch("/api/timer",{method:"POST",body:JSON.stringify({action:"start",task_id:id})});await load()};
 if(loading||!project)return <><PageHeader title="Projeto"/><LoadingBlock lines={9}/></>;
 const visibleTabs=project.project_type==="saas"?[...tabs.filter(t=>t!=="Clientes"),"SaaS"]:tabs;
 return <><PageHeader title={project.name} description={project.description||`${project.project_type==="saas"?"SaaS":project.project_type==="client"?"Projeto de cliente":"Projeto interno"} · ${project.status}`} actions={<><Button variant="secondary" onClick={openProjectEdit}><Pencil size={15}/> Editar</Button><Link href="/projetos" className="button button-secondary"><ArrowLeft size={15}/> Projetos</Link></>}/><div className="tabs">{visibleTabs.map(t=><button className={`tab ${tab===t?"active":""}`} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==="Visão geral"&&<><div className="kpi-grid"><KpiCard label="Receita líquida" value={formatMoney(summary?.revenue_net_cents||0)}/><KpiCard label="Lucro do projeto" value={formatMoney(summary?.profit_cents||0)} tone={(summary?.profit_cents||0)>=0?"positive":"negative"}/><KpiCard label="Parte Prodexy" value={formatMoney(summary?.prodexy_share_cents||0)} detail="Após distribuição societária"/><KpiCard label="Tempo no projeto" value={`${Math.floor(totalMinutes/60)}h ${totalMinutes%60}min`} detail={`${openTasks.length} demandas abertas`}/></div><div className="grid-2"><section className="panel"><div className="panel-header"><h2>Demandas abertas</h2><Link className="muted" href={`/demandas?projeto=${projectId}`}>Abrir demandas</Link></div><div className="panel-body">{openTasks.slice(0,6).map(t=><div className="alert-row" key={t.id}><Badge tone={t.priority==="critical"?"negative":t.priority==="high"?"warning":"neutral"}>{t.priority}</Badge><div><strong>{t.title}</strong><small>{t.due_at?`Prazo ${formatDateTime(t.due_at)}`:"Sem prazo"}</small></div><button className="icon-button" onClick={()=>startTimer(t.id)}><Play size={14}/></button></div>)}{openTasks.length===0&&<EmptyState title="Nenhuma demanda aberta"/>}</div></section><section className="panel"><div className="panel-header"><h2>Clientes</h2></div><div className="panel-body">{relatedClients.map((c:any)=><div className="alert-row" key={c.id}><div><strong>{c.name}</strong><small>{c.email||c.phone||"Sem contato cadastrado"}</small></div></div>)}{relatedClients.length===0&&<EmptyState title="Nenhum cliente relacionado"/>}</div></section></div></>}
 {tab==="Financeiro"&&<><div className="kpi-grid"><KpiCard label="Receita bruta" value={formatMoney(summary?.revenue_gross_cents||0)}/><KpiCard label="Taxas" value={formatMoney(summary?.revenue_fees_cents||0)}/><KpiCard label="Custos" value={formatMoney((summary?.direct_costs_cents||0)+(summary?.shared_costs_cents||0))} tone="negative"/><KpiCard label="Margem" value={summary?.margin_percentage==null?"—":formatPercent(summary.margin_percentage)}/></div><div className="section-title"><h2>Lançamentos</h2><Button onClick={()=>setTxOpen(true)}><Plus size={14}/> Lançamento</Button></div><section className="panel table-wrap"><table><thead><tr><th>Data</th><th>Descrição</th><th>Tipo</th><th className="numeric">Bruto</th><th className="numeric">Taxa</th><th className="numeric">Líquido</th></tr></thead><tbody>{transactions.slice(0,30).map(t=><tr key={t.id}><td>{formatDate(t.transaction_date)}</td><td>{t.description}</td><td><Badge tone={t.transaction_type==="revenue"?"positive":"negative"}>{t.transaction_type==="revenue"?"Receita":"Custo"}</Badge></td><td className="numeric">{formatMoney(t.gross_amount_cents)}</td><td className="numeric">{formatMoney(t.fee_amount_cents)}</td><td className="numeric">{formatMoney(t.net_amount_cents)}</td></tr>)}</tbody></table></section><TransactionModal open={txOpen} onClose={()=>setTxOpen(false)} onSaved={load} lookups={lookups} initialType="revenue" transaction={null} defaultProjectId={projectId}/></>}
 {tab==="Clientes"&&<><div className="section-title"><h2>Clientes relacionados</h2><Button onClick={()=>setClientModal(true)}><Plus size={14}/> Relacionar cliente</Button></div><section className="panel table-wrap"><table><thead><tr><th>Cliente</th><th>Contato</th><th>Status</th></tr></thead><tbody>{relatedClients.map((c:any)=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.email||c.phone||"—"}</td><td><Badge>{c.status}</Badge></td></tr>)}</tbody></table></section></>}
 {tab==="Demandas"&&<><div className="section-title"><h2>Demandas do projeto</h2><Link className="button button-primary" href={`/demandas?novo=1&projeto=${projectId}`}><Plus size={14}/> Nova demanda</Link></div><section className="panel table-wrap"><table><thead><tr><th>Demanda</th><th>Prioridade</th><th>Status</th><th>Prazo</th><th className="numeric">Estimativa</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td><Link href={`/demandas?tarefa=${t.id}`} className="table-link">{t.title}</Link></td><td><Badge>{t.priority}</Badge></td><td>{t.status}</td><td>{formatDateTime(t.due_at)}</td><td className="numeric">{t.estimated_minutes?`${t.estimated_minutes} min`:"—"}</td></tr>)}</tbody></table></section></>}
 {tab==="Metas"&&<section className="panel table-wrap"><table><thead><tr><th>Competência</th><th className="numeric">Meta clientes</th><th className="numeric">Implantação</th><th className="numeric">Recorrente</th><th className="numeric">Total</th></tr></thead><tbody>{goals.map(g=><tr key={g.id}><td>{g.competence_month?.slice(0,7)}</td><td className="numeric">{g.target_clients}</td><td className="numeric">{formatMoney(g.target_setup_revenue_cents)}</td><td className="numeric">{formatMoney(g.target_recurring_revenue_cents)}</td><td className="numeric"><strong>{formatMoney(g.target_total_revenue_cents)}</strong></td></tr>)}</tbody></table></section>}
 {tab==="Sócios"&&<><div className="section-title"><h2>Composição societária</h2><Button onClick={openNewPartner}><Plus size={14}/> Participação</Button></div>{activeProjectPartners.length===0?<div className="note" style={{marginBottom:12}}><strong>Composição atual: Prodexy Labs 100%</strong><div>Sem sócio externo vigente nesta competência.</div></div>:participationTotal===100?<div className="success-box" style={{marginBottom:12}}><strong>Composição atual: Prodexy Labs {formatPercent(holdingParticipation,2)} · Sócios externos {formatPercent(externalParticipation,2)}</strong></div>:<div className="warning-box" style={{marginBottom:12}}><strong>Composição incompleta: {formatPercent(participationTotal,2)} de 100%</strong><div>{participationTotal<100?`Faltam ${formatPercent(100-participationTotal,2)} para permitir o fechamento.`:`Excedente de ${formatPercent(participationTotal-100,2)}; ajuste os percentuais.`}</div></div>}<section className="panel table-wrap"><table><thead><tr><th>Participante</th><th>Tipo</th><th className="numeric">Participação</th><th>Vigência</th><th></th></tr></thead><tbody>{projectPartners.map(pp=>{const p:any=partnerMap.get(pp.partner_id);return <tr key={pp.id}><td><strong>{p?.name||"Participante"}</strong></td><td>{p?.partner_type==="holding"?"Prodexy":"Sócio externo"}</td><td className="numeric">{formatPercent(pp.participation_percentage,2)}</td><td>{formatDate(pp.start_date)} → {formatDate(pp.end_date)}</td><td><button className="icon-button" onClick={()=>openEditPartner(pp)} aria-label={`Editar participação de ${p?.name||"participante"}`} title="Editar participação"><Pencil size={14}/></button></td></tr>})}</tbody></table></section><div className="note" style={{marginTop:12}}>Para uma sociedade 50/50, registre Prodexy Labs com 50% e o sócio externo com 50%. Receitas e custos são lançados uma única vez no projeto; o fechamento abate os custos e divide somente o lucro líquido positivo. Prejuízo não gera cobrança automática ao sócio.</div></>}
 {tab==="Tempo"&&<><div className="kpi-grid"><KpiCard label="Tempo total registrado" value={`${Math.floor(totalMinutes/60)}h ${totalMinutes%60}min`}/><KpiCard label="Entradas de tempo" value={String(timeEntries.length)}/><KpiCard label="Lucro por hora" value={totalMinutes&&summary?formatMoney(Math.round((summary.prodexy_share_cents||0)/(totalMinutes/60))):"—"} detail="Indicador gerencial, não contábil"/></div><section className="panel table-wrap"><table><thead><tr><th>Início</th><th className="numeric">Minutos</th><th>Observação</th></tr></thead><tbody>{timeEntries.map(e=><tr key={e.id}><td>{formatDateTime(e.started_at)}</td><td className="numeric">{e.duration_minutes||"Em andamento"}</td><td>{e.notes||"—"}</td></tr>)}</tbody></table></section></>}
 {tab==="SaaS"&&<><div className="grid-2"><section className="panel"><div className="panel-header"><h2>Planos</h2><Button variant="secondary" onClick={()=>setPlanModal(true)}><Plus size={14}/> Plano</Button></div><div className="panel-body">{plans.map(p=><div className="alert-row" key={p.id}><div><strong>{p.name}</strong><small>{formatMoney(p.monthly_amount_cents)}/mês</small></div></div>)}{plans.length===0&&<EmptyState title="Nenhum plano"/>}</div></section><section className="panel"><div className="panel-header"><h2>Assinaturas</h2><Button variant="secondary" onClick={()=>setSubModal(true)}><Plus size={14}/> Assinatura</Button></div><div className="panel-body">{subscriptions.map(s=><div className="alert-row" key={s.id}><div><strong>{(clientMap.get(s.client_id) as any)?.name||"Cliente"}</strong><small>{formatMoney(s.monthly_amount_cents)} · {s.status}</small></div></div>)}{subscriptions.length===0&&<EmptyState title="Nenhuma assinatura"/>}</div></section></div></>}
 <Modal open={editProjectModal} onClose={()=>setEditProjectModal(false)} title="Editar projeto"><div className="form-grid"><div className="field full"><label>Nome</label><input className="input" value={projName} onChange={e=>setProjName(e.target.value)}/></div><div className="field"><label>Tipo</label><select className="select" value={projType} onChange={e=>setProjType(e.target.value)}><option value="client">Projeto de cliente</option><option value="saas">SaaS</option><option value="internal">Interno</option></select></div><div className="field"><label>Status</label><select className="select" value={projStatus} onChange={e=>setProjStatus(e.target.value)}><option value="active">Ativo</option><option value="paused">Pausado</option><option value="closed">Encerrado</option><option value="archived">Arquivado</option></select></div>{projType==="client"&&<div className="field full"><label>Cliente principal</label><select className="select" value={primaryClient} onChange={e=>setPrimaryClient(e.target.value)}><option value="">Não definido</option>{relatedClients.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>}<div className="field full"><label>Descrição</label><textarea className="textarea" value={projDescription} onChange={e=>setProjDescription(e.target.value)}/></div></div><div className="form-actions"><Button variant="secondary" onClick={()=>setEditProjectModal(false)}>Cancelar</Button><Button onClick={saveProject}>Salvar</Button></div></Modal>
 <Modal open={clientModal} onClose={()=>setClientModal(false)} title="Relacionar cliente"><div className="field"><label>Cliente</label><select className="select" value={selectedClient} onChange={e=>setSelectedClient(e.target.value)}><option value="">Selecione</option>{lookups.clients.filter(c=>!relations.some(r=>r.client_id===c.id)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="form-actions"><Button variant="secondary" onClick={()=>setClientModal(false)}>Cancelar</Button><Button onClick={addClient}>Relacionar</Button></div></Modal>
 <Modal open={partnerModal} onClose={()=>setPartnerModal(false)} title={partnerEditing?"Editar participação":"Adicionar participação"}>{partnerError&&<div className="error-box" style={{marginBottom:14}}>{partnerError}</div>}<div className="form-grid"><div className="field"><label>Participante</label><select className="select" value={partnerId} onChange={e=>{setPartnerId(e.target.value);setPartnerError("")}} disabled={!!partnerEditing}><option value="">Selecione</option>{lookups.partners.map(p=><option key={p.id} value={p.id}>{p.name} ({p.partner_type==="holding"?"Prodexy":"sócio externo"})</option>)}<option value="new-external">+ Cadastrar novo sócio externo</option></select></div><div className="field"><label>Participação (%)</label><input className="input" inputMode="decimal" value={pct} onChange={e=>setPct(e.target.value)} placeholder="50"/></div>{partnerId==="new-external"&&<div className="field full"><label>Nome do novo sócio</label><input className="input" value={newPartnerName} onChange={e=>setNewPartnerName(e.target.value)} autoFocus/></div>}<div className="field"><label>Início da vigência</label><input className="input" type="date" value={partnerStart} onChange={e=>setPartnerStart(e.target.value)} disabled={!!partnerEditing}/></div><div className="field"><label>Fim da vigência</label><input className="input" type="date" value={partnerEnd} min={partnerStart} onChange={e=>setPartnerEnd(e.target.value)}/></div></div><div className="note" style={{marginTop:10}}>No seu caso, salve Prodexy Labs com 50% e depois o sócio externo com 50%. A soma vigente precisa chegar a 100% antes do fechamento mensal.</div><div className="form-actions"><Button variant="secondary" onClick={()=>setPartnerModal(false)}>Cancelar</Button><Button onClick={savePartner}>Salvar participação</Button></div></Modal>
 <Modal open={planModal} onClose={()=>setPlanModal(false)} title="Novo plano"><div className="form-grid"><div className="field"><label>Nome</label><input className="input" value={planName} onChange={e=>setPlanName(e.target.value)}/></div><div className="field"><label>Mensalidade</label><input className="input" value={planValue} onChange={e=>setPlanValue(e.target.value)} placeholder="199,00"/></div></div><div className="form-actions"><Button variant="secondary" onClick={()=>setPlanModal(false)}>Cancelar</Button><Button onClick={addPlan}>Salvar</Button></div></Modal>
 <Modal open={subModal} onClose={()=>setSubModal(false)} title="Nova assinatura"><div className="form-grid"><div className="field"><label>Cliente</label><select className="select" value={subClient} onChange={e=>setSubClient(e.target.value)}><option value="">Selecione</option>{lookups.clients.filter(c=>c.status==="active"&&!subscriptions.some(s=>s.client_id===c.id&&["active","trial","overdue"].includes(s.status))).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Plano</label><select className="select" value={subPlan} onChange={e=>{setSubPlan(e.target.value);const p=plans.find(x=>x.id===e.target.value);if(p)setSubValue((p.monthly_amount_cents/100).toFixed(2).replace(".",","))}}><option value="">Personalizado</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Valor mensal</label><input className="input" value={subValue} onChange={e=>setSubValue(e.target.value)}/></div></div><div className="form-actions"><Button variant="secondary" onClick={()=>setSubModal(false)}>Cancelar</Button><Button onClick={addSubscription}>Salvar</Button></div></Modal>
 </>;
}
