"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Plus, Pencil } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { LoadingBlock } from "@/components/ui/loading";
import { EmptyState } from "@/components/ui/empty-state";
import { apiFetch, crudCreate, crudUpdate } from "@/lib/client-api";
import { useLookups } from "@/lib/use-lookups";
import { formatMoney } from "@/lib/money";
import { formatDate, todayInSaoPaulo } from "@/lib/date";

export default function ClientsPage(){
 const deepLinkHandled=useRef(false);const lookups=useLookups();const[clients,setClients]=useState<any[]>([]),[relations,setRelations]=useState<any[]>([]),[subs,setSubs]=useState<any[]>([]),[loading,setLoading]=useState(true);const[search,setSearch]=useState(""),[project,setProject]=useState("all"),[modal,setModal]=useState(false),[editing,setEditing]=useState<any>(null);const[name,setName]=useState(""),[company,setCompany]=useState(""),[contact,setContact]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[status,setStatus]=useState("active"),[entryDate,setEntryDate]=useState(""),[notes,setNotes]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{const[c,r,s]=await Promise.all([apiFetch<any[]>("/api/crud/clients?limit=2000"),apiFetch<any[]>("/api/crud/project-clients?limit=4000"),apiFetch<any[]>("/api/crud/subscriptions?limit=4000")]);setClients(c.filter(x=>x.status!=="archived"));setRelations(r);setSubs(s);}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 useEffect(()=>{const p=new URLSearchParams(window.location.search);if(p.get("novo"))openNew()},[]);useEffect(()=>{if(deepLinkHandled.current||!clients.length)return;const id=new URLSearchParams(window.location.search).get("cliente");if(id){const target=clients.find(c=>c.id===id);if(target)openEdit(target)}deepLinkHandled.current=true},[clients]);
 const projectMap=useMemo(()=>new Map(lookups.projects.map(p=>[p.id,p.name])),[lookups.projects]);
 const filtered=clients.filter(c=>(!search||`${c.name} ${c.company_name||""} ${c.contact_name||""} ${c.email||""}`.toLowerCase().includes(search.toLowerCase()))&&(project==="all"||relations.some(r=>r.client_id===c.id&&r.project_id===project&&r.active)));
 function openNew(){setEditing(null);setName("");setCompany("");setContact("");setPhone("");setEmail("");setStatus("active");setEntryDate(todayInSaoPaulo());setNotes("");setError("");setModal(true)}
 function openEdit(c:any){setEditing(c);setName(c.name);setCompany(c.company_name||"");setContact(c.contact_name||"");setPhone(c.phone||"");setEmail(c.email||"");setStatus(c.status);setEntryDate(c.entry_date||"");setNotes(c.notes||"");setError("");setModal(true)}
 const save=async()=>{if(!name.trim()){setError("Nome obrigatório.");return}setSaving(true);setError("");const payload={name:name.trim(),company_name:company||null,contact_name:contact||null,phone:phone||null,email:email||null,status,entry_date:entryDate||null,notes:notes||null};try{editing?await crudUpdate("clients",editing.id,payload):await crudCreate("clients",payload);setModal(false);await load();await lookups.refresh()}catch(e){setError(e instanceof Error?e.message:"Erro ao salvar.")}finally{setSaving(false)}};
 return <><PageHeader title="Clientes" description="Cadastro central: projetos, assinaturas, demandas e financeiro podem apontar para o mesmo cliente." actions={<Button onClick={openNew}><Plus size={15}/> Novo cliente</Button>}/><div className="filter-bar"><div className="field grow"><label>Buscar</label><input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, empresa, contato ou e-mail"/></div><div className="field"><label>Projeto</label><select className="select" value={project} onChange={e=>setProject(e.target.value)}><option value="all">Todos</option>{lookups.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></div></div>
 {loading?<LoadingBlock lines={7}/>:<section className="panel table-wrap">{filtered.length===0?<EmptyState title="Nenhum cliente encontrado"/>:<table><thead><tr><th>Cliente</th><th>Contato</th><th>Projetos</th><th>Assinaturas</th><th>Status</th><th>Entrada</th><th></th></tr></thead><tbody>{filtered.map(c=>{const rel=relations.filter(r=>r.client_id===c.id&&r.active);const activeSubs=subs.filter(s=>s.client_id===c.id&&["active","trial","overdue"].includes(s.status));return <tr key={c.id}><td><strong>{c.name}</strong>{c.company_name&&c.company_name!==c.name&&<div className="muted">{c.company_name}</div>}</td><td>{c.contact_name||"—"}<div className="muted">{c.email||c.phone||""}</div></td><td>{rel.length?rel.map(r=>projectMap.get(r.project_id)||"Projeto").join(" · "):"—"}</td><td>{activeSubs.length?<div>{activeSubs.map(s=><div key={s.id}>{projectMap.get(s.project_id)||"SaaS"}: <strong>{formatMoney(s.monthly_amount_cents)}/mês</strong></div>)}</div>:"—"}</td><td><Badge tone={c.status==="active"?"positive":c.status==="cancelled"?"negative":"neutral"}>{c.status}</Badge></td><td>{formatDate(c.entry_date)}</td><td><button className="icon-button" onClick={()=>openEdit(c)}><Pencil size={14}/></button></td></tr>})}</tbody></table>}</section>}
 <Modal open={modal} onClose={()=>setModal(false)} title={editing?"Editar cliente":"Novo cliente"}>{error&&<div className="error-box" style={{marginBottom:14}}>{error}</div>}<div className="form-grid"><div className="field"><label>Nome</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>Empresa</label><input className="input" value={company} onChange={e=>setCompany(e.target.value)}/></div><div className="field"><label>Pessoa de contato</label><input className="input" value={contact} onChange={e=>setContact(e.target.value)}/></div><div className="field"><label>Telefone</label><input className="input" value={phone} onChange={e=>setPhone(e.target.value)}/></div><div className="field"><label>E-mail</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="field"><label>Status</label><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Ativo</option><option value="inactive">Inativo</option><option value="cancelled">Cancelado</option><option value="lead">Lead</option></select></div><div className="field"><label>Data de entrada</label><input className="input" type="date" value={entryDate} onChange={e=>setEntryDate(e.target.value)}/></div><div className="field full"><label>Observações</label><textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)}/></div></div><div className="form-actions"><Button variant="secondary" onClick={()=>setModal(false)}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?"Salvando...":"Salvar cliente"}</Button></div></Modal></>;
}
